#include "ZzExampleRouteCatalog.h"

#include <array>

#include <QtCore/QCoreApplication>

namespace ZzExample {

namespace {

using ZzLifetime = ZzPureTools::ZzPageLifetimePolicy;
using ZzPlacement = ZzFluentUI::ZzNavigationPlacement;

constexpr std::array<ZzExampleRouteDescriptor, 40> zzRoutes{{
    {"home", QT_TRANSLATE_NOOP("ZzPureToolsExample", "首页"),
     QT_TRANSLATE_NOOP("ZzPureToolsExample", "工作区"),
     ZzLifetime::Persistent,
     ZzPlacement::Primary},
    {"push-button", QT_TRANSLATE_NOOP("ZzPureToolsExample", "按钮(PushButton)"),
     QT_TRANSLATE_NOOP("ZzPureToolsExample", "基础控件"), ZzLifetime::Recreatable, ZzPlacement::Primary,
     ZzExampleControlKind::PushButton},
    {"icon-button", QT_TRANSLATE_NOOP("ZzPureToolsExample", "图标按钮(IconButton)"),
     "", ZzLifetime::Recreatable, ZzPlacement::Primary,
     ZzExampleControlKind::IconButton},
    {"tool-button", QT_TRANSLATE_NOOP("ZzPureToolsExample", "工具按钮(ToolButton)"),
     "", ZzLifetime::Recreatable, ZzPlacement::Primary,
     ZzExampleControlKind::ToolButton},
    {"radio-button", QT_TRANSLATE_NOOP("ZzPureToolsExample", "单选框(RadioButton)"),
     "", ZzLifetime::Recreatable, ZzPlacement::Primary,
     ZzExampleControlKind::RadioButton},
    {"check-box", QT_TRANSLATE_NOOP("ZzPureToolsExample", "复选框(CheckBox)"),
     "", ZzLifetime::Recreatable, ZzPlacement::Primary,
     ZzExampleControlKind::CheckBox},
    {"toggle-switch", QT_TRANSLATE_NOOP("ZzPureToolsExample", "开关(ToggleSwitch)"),
     "", ZzLifetime::Recreatable, ZzPlacement::Primary,
     ZzExampleControlKind::ToggleSwitch},
    {"line-edit", QT_TRANSLATE_NOOP("ZzPureToolsExample", "单行输入(LineEdit)"),
     "", ZzLifetime::Recreatable, ZzPlacement::Primary,
     ZzExampleControlKind::LineEdit},
    {"plain-text-edit", QT_TRANSLATE_NOOP("ZzPureToolsExample", "多行输入(PlainTextEdit)"),
     "", ZzLifetime::Recreatable, ZzPlacement::Primary,
     ZzExampleControlKind::PlainTextEdit},
    {"combo-box", QT_TRANSLATE_NOOP("ZzPureToolsExample", "组合框(ComboBox)"),
     "", ZzLifetime::Recreatable, ZzPlacement::Primary,
     ZzExampleControlKind::ComboBox},
    {"multi-select-combo-box", QT_TRANSLATE_NOOP("ZzPureToolsExample", "多选组合框(MultiSelectComboBox)"),
     "", ZzLifetime::Recreatable, ZzPlacement::Primary,
     ZzExampleControlKind::MultiSelectComboBox},
    {"spin-box", QT_TRANSLATE_NOOP("ZzPureToolsExample", "整数输入(SpinBox)"),
     "", ZzLifetime::Recreatable, ZzPlacement::Primary,
     ZzExampleControlKind::SpinBox},
    {"double-spin-box", QT_TRANSLATE_NOOP("ZzPureToolsExample", "小数输入(DoubleSpinBox)"),
     "", ZzLifetime::Recreatable, ZzPlacement::Primary,
     ZzExampleControlKind::DoubleSpinBox},
    {"calendar-picker", QT_TRANSLATE_NOOP("ZzPureToolsExample", "日期选择(CalendarPicker)"),
     "", ZzLifetime::Recreatable, ZzPlacement::Primary,
     ZzExampleControlKind::CalendarPicker},
    {"roller-picker", QT_TRANSLATE_NOOP("ZzPureToolsExample", "滚轮选择(RollerPicker)"),
     "", ZzLifetime::Recreatable, ZzPlacement::Primary,
     ZzExampleControlKind::RollerPicker},
    {"slider", QT_TRANSLATE_NOOP("ZzPureToolsExample", "滑块(Slider)"),
     "", ZzLifetime::Recreatable, ZzPlacement::Primary,
     ZzExampleControlKind::Slider},
    {"scroll-bar", QT_TRANSLATE_NOOP("ZzPureToolsExample", "滚动条(ScrollBar)"),
     "", ZzLifetime::Recreatable, ZzPlacement::Primary,
     ZzExampleControlKind::ScrollBar},
    {"progress-bar", QT_TRANSLATE_NOOP("ZzPureToolsExample", "进度条(ProgressBar)"),
     "", ZzLifetime::Recreatable, ZzPlacement::Primary,
     ZzExampleControlKind::ProgressBar},
    {"group-box", QT_TRANSLATE_NOOP("ZzPureToolsExample", "分组框(GroupBox)"),
     "", ZzLifetime::Recreatable, ZzPlacement::Primary,
     ZzExampleControlKind::GroupBox},
    {"tab-bar", QT_TRANSLATE_NOOP("ZzPureToolsExample", "标签栏(TabBar)"),
     "", ZzLifetime::Recreatable, ZzPlacement::Primary},
    {"range-slider", QT_TRANSLATE_NOOP("ZzPureToolsExample", "范围滑块(RangeSlider)"),
     QT_TRANSLATE_NOOP("ZzPureToolsExample", "自定义控件"),
     ZzLifetime::Recreatable, ZzPlacement::Primary},
    {"border-beam", QT_TRANSLATE_NOOP("ZzPureToolsExample", "边框光束(BorderBeam)"),
     "", ZzLifetime::Recreatable, ZzPlacement::Primary},
    {"audio-level-meter", QT_TRANSLATE_NOOP("ZzPureToolsExample", "音频电平表(AudioLevelMeter)"),
     "", ZzLifetime::Recreatable, ZzPlacement::Primary},
    {"radial-gauge", QT_TRANSLATE_NOOP("ZzPureToolsExample", "径向仪表盘(RadialGauge)"),
     "", ZzLifetime::Recreatable, ZzPlacement::Primary},
    {"liquid-gauge", QT_TRANSLATE_NOOP("ZzPureToolsExample", "水波进度球(LiquidGauge)"),
     "", ZzLifetime::Recreatable, ZzPlacement::Primary},
    {"progress-ring", QT_TRANSLATE_NOOP("ZzPureToolsExample", "环形进度条(ProgressRing)"),
     "", ZzLifetime::Recreatable, ZzPlacement::Primary},
    {"timeline", QT_TRANSLATE_NOOP("ZzPureToolsExample", "时间轴(Timeline)"),
     "", ZzLifetime::Recreatable, ZzPlacement::Primary},
    {"info-bar", QT_TRANSLATE_NOOP("ZzPureToolsExample", "信息栏(InfoBar)"),
     "", ZzLifetime::Recreatable, ZzPlacement::Primary},
    {"carousel", QT_TRANSLATE_NOOP("ZzPureToolsExample", "轮播图(Carousel)"),
     "", ZzLifetime::Recreatable, ZzPlacement::Primary},
    {"cards", QT_TRANSLATE_NOOP("ZzPureToolsExample", "卡片与媒体"),
     QT_TRANSLATE_NOOP("ZzPureToolsExample", "控件"),
     ZzLifetime::Recreatable,
     ZzPlacement::Primary},
    {"list-view", QT_TRANSLATE_NOOP("ZzPureToolsExample", "列表视图"),
     QT_TRANSLATE_NOOP("ZzPureToolsExample", "数据视图"),
     ZzLifetime::Recreatable,
     ZzPlacement::Primary},
    {"table-view", QT_TRANSLATE_NOOP("ZzPureToolsExample", "表格视图"), "",
     ZzLifetime::Recreatable,
     ZzPlacement::Primary},
    {"tree-view", QT_TRANSLATE_NOOP("ZzPureToolsExample", "树形视图"), "",
     ZzLifetime::Recreatable,
     ZzPlacement::Primary},
    {"navigation", QT_TRANSLATE_NOOP("ZzPureToolsExample", "导航与历史"),
     QT_TRANSLATE_NOOP("ZzPureToolsExample", "交互"),
     ZzLifetime::Recreatable,
     ZzPlacement::Primary},
    {"feedback", QT_TRANSLATE_NOOP(
                     "ZzPureToolsExample", "反馈与弹出层"),
     "", ZzLifetime::Recreatable,
     ZzPlacement::Primary},
    {"selection-indicators", QT_TRANSLATE_NOOP("ZzPureToolsExample", "选中指示条对比"),
     "", ZzLifetime::Recreatable, ZzPlacement::Primary},
    {"message-bar", QT_TRANSLATE_NOOP("ZzPureToolsExample", "消息条(MessageBar)"),
     QT_TRANSLATE_NOOP("ZzPureToolsExample", "反馈与状态"),
     ZzLifetime::Recreatable, ZzPlacement::Primary, ZzExampleControlKind::MessageBar},
    {"info-badge", QT_TRANSLATE_NOOP("ZzPureToolsExample", "信息徽标(InfoBadge)"),
     "", ZzLifetime::Recreatable, ZzPlacement::Primary, ZzExampleControlKind::InfoBadge},
    {"icons", QT_TRANSLATE_NOOP("ZzPureToolsExample", "图标"),
     QT_TRANSLATE_NOOP("ZzPureToolsExample", "资源"),
     ZzLifetime::Recreatable,
     ZzPlacement::Primary},
    {"platform", QT_TRANSLATE_NOOP("ZzPureToolsExample", "窗口与平台"),
     QT_TRANSLATE_NOOP("ZzPureToolsExample", "系统"),
     ZzLifetime::Persistent,
     ZzPlacement::Primary},
}};

} // namespace

std::span<const ZzExampleRouteDescriptor>
ZzExampleRouteCatalog::routes() noexcept
{
    return zzRoutes;
}

} // namespace ZzExample
