#pragma once

#define ZZLOG_VERSION_MAJOR 0
#define ZZLOG_VERSION_MINOR 1
#define ZZLOG_VERSION_PATCH 0

#define ZZLOG_VERSION_NUMBER (ZZLOG_VERSION_MAJOR * 10000 + ZZLOG_VERSION_MINOR * 100 + ZZLOG_VERSION_PATCH)
