#ifndef ZZPURETOOLS_CORE_ZZPURETOOLSGLOBAL_HPP
#define ZZPURETOOLS_CORE_ZZPURETOOLSGLOBAL_HPP

#include <QtCore/qglobal.h>

#if defined(ZZ_PURE_TOOLS_LIBRARY)
#  define ZZ_PURE_TOOLS_EXPORT Q_DECL_EXPORT
#else
#  define ZZ_PURE_TOOLS_EXPORT Q_DECL_IMPORT
#endif

#endif // ZZPURETOOLS_CORE_ZZPURETOOLSGLOBAL_HPP
