#ifndef ZZPURETOOLS_CORE_ZZPURETOOLSGLOBAL_HPP
#define ZZPURETOOLS_CORE_ZZPURETOOLSGLOBAL_HPP

#include <QtCore/qglobal.h>

/**
 * @def ZZ_PURE_TOOLS_EXPORT
 * @brief ZzPureTools 库符号导出/导入宏。
 *
 * 编译库时定义为 Q_DECL_EXPORT，使用库时定义为 Q_DECL_IMPORT。
 */
#if defined(ZZ_PURE_TOOLS_LIBRARY)
#  define ZZ_PURE_TOOLS_EXPORT Q_DECL_EXPORT
#else
#  define ZZ_PURE_TOOLS_EXPORT Q_DECL_IMPORT
#endif

#endif // ZZPURETOOLS_CORE_ZZPURETOOLSGLOBAL_HPP
