cmake_minimum_required(VERSION 3.23)

foreach(required ZZ_SOURCE_DIR ZZ_SCAN_ROOT ZZ_ALLOWLIST)
    if(NOT DEFINED ${required} OR "${${required}}" STREQUAL "")
        message(FATAL_ERROR "Missing -D${required}=...")
    endif()
endforeach()

list(PREPEND CMAKE_MODULE_PATH "${ZZ_SOURCE_DIR}/cmake")
include(ZzArchitectureChecks)
set_property(GLOBAL PROPERTY ZZ_ARCHITECTURE_FINDINGS "")
zz_architecture_begin_visual_scan("${ZZ_ALLOWLIST}")
file(GLOB_RECURSE source_files LIST_DIRECTORIES FALSE
    "${ZZ_SCAN_ROOT}/*.h" "${ZZ_SCAN_ROOT}/*.cpp")
foreach(source_file IN LISTS source_files)
    zz_architecture_scan_visual_source("${ZZ_SCAN_ROOT}" "${source_file}")
endforeach()
zz_architecture_finalize_visual_scan()
get_property(findings GLOBAL PROPERTY ZZ_ARCHITECTURE_FINDINGS)
if(findings)
    list(JOIN findings "\n" finding_text)
    message(FATAL_ERROR "Visual token fixture failed:\n${finding_text}")
endif()
message(STATUS "Fluent visual token fixture passed")
