cmake_minimum_required(VERSION 3.23)

foreach(required ZZ_RUN_DIRECTORIES ZZ_OUTPUT_JSON ZZ_OUTPUT_MARKDOWN)
    if(NOT DEFINED ${required} OR "${${required}}" STREQUAL "")
        message(FATAL_ERROR "Missing -D${required}=...")
    endif()
endforeach()

set(run_directories ${ZZ_RUN_DIRECTORIES})
list(LENGTH run_directories run_count)
if(run_count LESS 3)
    message(FATAL_ERROR "ZZ_RUN_DIRECTORIES must contain at least three directories")
endif()
foreach(run_directory IN LISTS run_directories)
    if(NOT IS_DIRECTORY "${run_directory}")
        message(FATAL_ERROR "Performance run directory does not exist: ${run_directory}")
    endif()
endforeach()

function(zz_noise_json_get output json_text label)
    string(JSON value ERROR_VARIABLE json_error GET "${json_text}" ${ARGN})
    if(NOT "${json_error}" STREQUAL "NOTFOUND")
        message(FATAL_ERROR
            "${label} has invalid/missing JSON path ${ARGN}: ${json_error}")
    endif()
    set(${output} "${value}" PARENT_SCOPE)
endfunction()

function(zz_noise_decimal_to_micro output input)
    if(NOT "${input}" MATCHES "^([0-9]+)(\\.([0-9]+))?$")
        message(FATAL_ERROR "Not a non-negative decimal: ${input}")
    endif()
    set(whole "${CMAKE_MATCH_1}")
    set(fraction "${CMAKE_MATCH_3}")
    string(REGEX REPLACE "^0+" "" whole "${whole}")
    if("${whole}" STREQUAL "")
        set(whole 0)
    endif()
    string(APPEND fraction "000000")
    string(SUBSTRING "${fraction}" 0 6 fraction)
    math(EXPR value "${whole} * 1000000 + ${fraction}")
    set(${output} "${value}" PARENT_SCOPE)
endfunction()

list(GET run_directories 0 reference_directory)
file(GLOB reference_reports LIST_DIRECTORIES FALSE
    "${reference_directory}/benchmark.*.json")
list(SORT reference_reports)
if(NOT reference_reports)
    message(FATAL_ERROR "No benchmark reports found in ${reference_directory}")
endif()

set(reference_names)
foreach(reference_report IN LISTS reference_reports)
    get_filename_component(report_name "${reference_report}" NAME)
    list(APPEND reference_names "${report_name}")
endforeach()
foreach(run_directory IN LISTS run_directories)
    file(GLOB run_reports LIST_DIRECTORIES FALSE
        "${run_directory}/benchmark.*.json")
    set(run_names)
    foreach(run_report IN LISTS run_reports)
        get_filename_component(report_name "${run_report}" NAME)
        list(APPEND run_names "${report_name}")
    endforeach()
    list(SORT run_names)
    if(NOT "${run_names}" STREQUAL "${reference_names}")
        message(FATAL_ERROR
            "Benchmark report set differs in ${run_directory}")
    endif()
endforeach()

set(candidate_json [=[{"schemaVersion":1,"scenarios":{}}]=])
set(markdown "# Linux benchmark 跨轮噪声候选\n\n")
string(APPEND markdown
    "| 场景 | 指标 | 字段 | 波动 | 建议模式 | 建议门限 |\n"
    "|---|---|---|---:|---|---:|\n")

foreach(report_name IN LISTS reference_names)
    set(run_jsons)
    foreach(run_directory IN LISTS run_directories)
        file(READ "${run_directory}/${report_name}" run_json)
        list(APPEND run_jsons "${run_json}")
    endforeach()
    list(GET run_jsons 0 reference_json)
    zz_noise_json_get(scenario "${reference_json}" "Reference" scenario)
    zz_noise_json_get(schema "${reference_json}" "Reference" schemaVersion)
    zz_noise_json_get(environment "${reference_json}" "Reference" environment)
    if(NOT "${schema}" STREQUAL "1" OR NOT scenario MATCHES "^[a-z0-9-]+$")
        message(FATAL_ERROR "Invalid schema or scenario in ${report_name}")
    endif()
    foreach(run_json IN LISTS run_jsons)
        zz_noise_json_get(current_scenario "${run_json}" "Run" scenario)
        zz_noise_json_get(current_schema "${run_json}" "Run" schemaVersion)
        zz_noise_json_get(current_environment "${run_json}" "Run" environment)
        if(NOT "${current_scenario}" STREQUAL "${scenario}"
           OR NOT "${current_schema}" STREQUAL "${schema}"
           OR NOT "${current_environment}" STREQUAL "${environment}")
            message(FATAL_ERROR
                "Schema, scenario, or environment mismatch in ${report_name}")
        endif()
    endforeach()

    string(JSON metric_count LENGTH "${reference_json}" metrics)
    if(metric_count LESS 1)
        message(FATAL_ERROR "Metrics are empty in ${report_name}")
    endif()
    string(JSON candidate_json SET "${candidate_json}"
        scenarios "${scenario}" [=[{"metrics":{}}]=])
    math(EXPR last_metric "${metric_count} - 1")
    foreach(metric_index RANGE 0 ${last_metric})
        string(JSON metric MEMBER "${reference_json}" metrics ${metric_index})
        if(NOT metric MATCHES "^[a-z0-9-]+$")
            message(FATAL_ERROR "Invalid metric name in ${report_name}: ${metric}")
        endif()
        zz_noise_json_get(reference_unit "${reference_json}" "Reference"
            metrics "${metric}" unit)
        foreach(run_json IN LISTS run_jsons)
            string(JSON current_metric_count LENGTH "${run_json}" metrics)
            zz_noise_json_get(current_unit "${run_json}" "Run"
                metrics "${metric}" unit)
            if(NOT current_metric_count EQUAL metric_count
               OR NOT "${current_unit}" STREQUAL "${reference_unit}")
                message(FATAL_ERROR
                    "Metric set or unit mismatch for ${scenario}.${metric}")
            endif()
        endforeach()
        string(JSON candidate_json SET "${candidate_json}"
            scenarios "${scenario}" metrics "${metric}" "{}")

        foreach(field p95 max)
            set(minimum_micro)
            set(maximum_micro 0)
            foreach(run_json IN LISTS run_jsons)
                zz_noise_json_get(value "${run_json}" "Run"
                    metrics "${metric}" "${field}")
                zz_noise_decimal_to_micro(value_micro "${value}")
                if("${minimum_micro}" STREQUAL ""
                   OR value_micro LESS minimum_micro)
                    set(minimum_micro "${value_micro}")
                endif()
                if(value_micro GREATER maximum_micro)
                    set(maximum_micro "${value_micro}")
                endif()
            endforeach()
            if(minimum_micro EQUAL 0)
                if(maximum_micro EQUAL 0)
                    set(noise_percent 0)
                else()
                    set(noise_percent 101)
                endif()
            else()
                math(EXPR delta_micro "${maximum_micro} - ${minimum_micro}")
                math(EXPR noise_percent
                    "(${delta_micro} * 100 + ${minimum_micro} - 1) / ${minimum_micro}")
            endif()
            if(noise_percent GREATER 20)
                set(mode observe)
                set(threshold "${noise_percent}")
                if(threshold GREATER 100)
                    set(threshold 100)
                endif()
            elseif(noise_percent GREATER 10)
                set(mode gate)
                set(threshold "${noise_percent}")
            else()
                set(mode gate)
                set(threshold 10)
            endif()
            string(JSON policy SET "{}" mode "\"${mode}\"")
            string(JSON policy SET "${policy}" percent "${threshold}")
            string(JSON policy SET "${policy}" noisePercent "${noise_percent}")
            string(JSON candidate_json SET "${candidate_json}"
                scenarios "${scenario}" metrics "${metric}" "${field}"
                "${policy}")
            string(APPEND markdown
                "| ${scenario} | ${metric} | ${field} | ${noise_percent}% | ${mode} | ${threshold}% |\n")
        endforeach()
    endforeach()
endforeach()

get_filename_component(json_directory "${ZZ_OUTPUT_JSON}" DIRECTORY)
get_filename_component(markdown_directory "${ZZ_OUTPUT_MARKDOWN}" DIRECTORY)
file(MAKE_DIRECTORY "${json_directory}" "${markdown_directory}")
file(WRITE "${ZZ_OUTPUT_JSON}" "${candidate_json}\n")
file(WRITE "${ZZ_OUTPUT_MARKDOWN}" "${markdown}")
message(STATUS
    "Analyzed ${run_count} performance rounds into ${ZZ_OUTPUT_JSON}")
