#ifndef ZZFLUENTCOREGLOBAL_H
#define ZZFLUENTCOREGLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ZZ_FLUENT_CORE_LIBRARY)
#  define ZZ_CORE_EXPORT Q_DECL_EXPORT
#else
#  define ZZ_CORE_EXPORT Q_DECL_IMPORT
#endif

#endif // ZZFLUENTCOREGLOBAL_H
