#ifndef ZZFLUENT_CORE_ZZFLUENTGLOBAL_HPP
#define ZZFLUENT_CORE_ZZFLUENTGLOBAL_HPP

#include <QtCore/qglobal.h>

#if defined(ZZ_FLUENT_LIBRARY)
#  define ZZ_FLUENT_EXPORT Q_DECL_EXPORT
#else
#  define ZZ_FLUENT_EXPORT Q_DECL_IMPORT
#endif

#endif // ZZFLUENT_CORE_ZZFLUENTGLOBAL_HPP
