foreach(required ZZ_BASELINE ZZ_CURRENT ZZ_THRESHOLDS)
    if(NOT DEFINED ${required} OR "${${required}}" STREQUAL "")
        message(FATAL_ERROR "Missing -D${required}=...")
    endif()
    if(NOT EXISTS "${${required}}")
        message(FATAL_ERROR "Performance report does not exist: ${${required}}")
    endif()
endforeach()

file(READ "${ZZ_BASELINE}" baseline_json)
file(READ "${ZZ_CURRENT}" current_json)
file(READ "${ZZ_THRESHOLDS}" thresholds_json)

function(zz_invalid context detail)
    message(FATAL_ERROR "INVALID ${context}: ${detail}")
endfunction()

function(zz_json_get output json_text context)
    string(JSON value ERROR_VARIABLE json_error GET "${json_text}" ${ARGN})
    if(NOT "${json_error}" STREQUAL "NOTFOUND")
        zz_invalid("${context}" "invalid/missing JSON path ${ARGN}: ${json_error}")
    endif()
    set(${output} "${value}" PARENT_SCOPE)
endfunction()

function(zz_json_require_type json_text context expected_type)
    string(JSON actual_type ERROR_VARIABLE json_error TYPE "${json_text}" ${ARGN})
    if(NOT "${json_error}" STREQUAL "NOTFOUND" OR NOT "${actual_type}" STREQUAL "${expected_type}")
        zz_invalid("${context}" "JSON path ${ARGN} must be ${expected_type}")
    endif()
endfunction()

function(zz_require_commit json_text context)
    zz_json_get(commit "${json_text}" "${context}" build commit)
    string(LENGTH "${commit}" commit_length)
    if(NOT commit_length EQUAL 40 OR NOT "${commit}" MATCHES "^[0-9a-f]+$")
        zz_invalid("${context}" "build.commit must be 40 lowercase hex characters")
    endif()
endfunction()

function(zz_decimal_to_micro output input context)
    if(NOT "${input}" MATCHES "^([0-9]+)(\\.([0-9]+))?$")
        zz_invalid("${context}" "must be a non-negative decimal: ${input}")
    endif()
    set(whole "${CMAKE_MATCH_1}")
    set(fraction "${CMAKE_MATCH_3}")
    string(REGEX REPLACE "^0+" "" normalized_whole "${whole}")
    if("${normalized_whole}" STREQUAL "")
        set(normalized_whole 0)
    endif()
    string(APPEND fraction "000000")
    string(SUBSTRING "${fraction}" 0 6 fraction)
    string(LENGTH "${normalized_whole}" whole_length)
    if(whole_length GREATER 13
       OR (whole_length EQUAL 13 AND "${normalized_whole}" STRGREATER "9223372036854")
       OR ("${normalized_whole}" STREQUAL "9223372036854" AND "${fraction}" STRGREATER "775807"))
        zz_invalid("${context}" "exceeds signed 64-bit millionths: ${input}")
    endif()
    math(EXPR micro "${normalized_whole} * 1000000 + ${fraction}")
    set(${output} "${micro}" PARENT_SCOPE)
endfunction()

function(zz_validate_policy scenario metric kind field mode percent)
    set(context "${scenario}/${metric}")
    if(NOT "${percent}" MATCHES "^[0-9]+$" OR "${percent}" GREATER 100)
        zz_invalid("${context}" "${field}.percent must be a JSON integer from 0 to 100")
    endif()
    if("${kind}" STREQUAL "statistical-duration")
        if("${field}" STREQUAL "p95")
            if(NOT "${mode}" STREQUAL "gate" AND NOT "${mode}" STREQUAL "observe")
                zz_invalid("${context}" "p95.mode must be gate or observe")
            endif()
            if("${mode}" STREQUAL "gate" AND "${percent}" GREATER 10)
                zz_invalid("${context}" "p95 gate percent must not exceed 10")
            endif()
        elseif("${field}" STREQUAL "max")
            if(NOT "${mode}" STREQUAL "observe")
                zz_invalid("${context}" "max.mode must be observe")
            endif()
        else()
            zz_invalid("${context}" "unknown policy field ${field}")
        endif()
    elseif("${kind}" STREQUAL "deterministic" OR "${kind}" STREQUAL "sampled-resource")
        if(NOT "${mode}" STREQUAL "gate")
            zz_invalid("${context}" "${field}.mode must be gate")
        endif()
        if("${percent}" GREATER 20)
            zz_invalid("${context}" "${field} gate percent must not exceed 20")
        endif()
    else()
        zz_invalid("${context}" "metricKind must be statistical-duration, deterministic, or sampled-resource")
    endif()
endfunction()

function(zz_assert_regression output scenario metric field baseline_value current_value mode percent)
    set(context "${scenario}/${metric}")
    zz_decimal_to_micro(baseline_micro "${baseline_value}" "${context}.${field}")
    zz_decimal_to_micro(current_micro "${current_value}" "${context}.${field}")
    math(EXPR whole_increment "(${baseline_micro} / 100) * ${percent}")
    math(EXPR remainder_increment "((${baseline_micro} % 100) * ${percent}) / 100")
    set(maximum_signed_64 9223372036854775807)
    math(EXPR available_increment "${maximum_signed_64} - ${baseline_micro}")
    if("${whole_increment}" GREATER "${available_increment}")
        set(allowed_micro "${maximum_signed_64}")
    else()
        math(EXPR remaining_increment "${available_increment} - ${whole_increment}")
        if("${remainder_increment}" GREATER "${remaining_increment}")
            set(allowed_micro "${maximum_signed_64}")
        else()
            math(EXPR allowed_micro "${baseline_micro} + ${whole_increment} + ${remainder_increment}")
        endif()
    endif()
    if(baseline_micro EQUAL 0)
        if(current_micro EQUAL 0)
            set(change "0%")
        else()
            set(change "new-nonzero")
        endif()
    elseif(current_micro GREATER_EQUAL baseline_micro)
        math(EXPR increase "${current_micro} - ${baseline_micro}")
        if(increase GREATER 92233720368547758)
            set(change ">=100%")
        else()
            math(EXPR change_percent "(${increase} * 100) / ${baseline_micro}")
            set(change "${change_percent}%")
        endif()
    else()
        math(EXPR decrease "${baseline_micro} - ${current_micro}")
        if(decrease GREATER 92233720368547758)
            set(change "<=-100%")
        else()
            math(EXPR change_percent "(${decrease} * 100) / ${baseline_micro}")
            set(change "-${change_percent}%")
        endif()
    endif()
    if(current_micro GREATER allowed_micro)
        if("${mode}" STREQUAL "observe")
            set(status OBSERVE)
        else()
            set(status FAIL)
        endif()
    else()
        set(status PASS)
    endif()
    message(STATUS "${status} ${scenario}/${metric}.${field} baseline=${baseline_value} current=${current_value} change=${change} mode=${mode} band=${percent}%")
    set(${output} "${status}" PARENT_SCOPE)
endfunction()

zz_json_require_type("${baseline_json}" baseline NUMBER schemaVersion)
zz_json_require_type("${current_json}" current NUMBER schemaVersion)
zz_json_require_type("${thresholds_json}" thresholds NUMBER schemaVersion)
zz_json_get(baseline_schema "${baseline_json}" baseline schemaVersion)
zz_json_get(current_schema "${current_json}" current schemaVersion)
zz_json_get(baseline_scenario "${baseline_json}" baseline scenario)
zz_json_get(current_scenario "${current_json}" current scenario)
zz_json_get(threshold_schema "${thresholds_json}" thresholds schemaVersion)
if(NOT "${baseline_schema}" STREQUAL "1" OR NOT "${current_schema}" STREQUAL "1")
    zz_invalid("${current_scenario}" "baseline and current reporter schemaVersion must be 1")
endif()
if(NOT "${threshold_schema}" STREQUAL "2")
    zz_invalid(thresholds "schemaVersion must be 2")
endif()
if("${baseline_scenario}" STREQUAL "" OR NOT "${current_scenario}" STREQUAL "${baseline_scenario}")
    zz_invalid("${current_scenario}" "baseline/current scenario mismatch")
endif()
zz_require_commit("${baseline_json}" "${current_scenario}")
zz_require_commit("${current_json}" "${current_scenario}")

foreach(fingerprint_path IN ITEMS
    "environment;cpu" "environment;memoryBytes" "environment;os" "environment;gpu"
    "environment;runnerImageDigest" "environment;qtVersion" "environment;compiler"
    "environment;windowSystem" "environment;dpr" "environment;refreshRateHz"
    "build;buildType" "build;shared" "build;lto" "build;sanitizers")
    zz_json_get(baseline_value "${baseline_json}" "${current_scenario} ${fingerprint_path}" ${fingerprint_path})
    zz_json_get(current_value "${current_json}" "${current_scenario} ${fingerprint_path}" ${fingerprint_path})
    if(NOT "${current_value}" STREQUAL "${baseline_value}")
        zz_invalid("${current_scenario} ${fingerprint_path}" "baseline=${baseline_value}, current=${current_value}")
    endif()
endforeach()

zz_json_get(baseline_preset "${baseline_json}" "${current_scenario} build;preset" build preset)
zz_json_get(current_preset "${current_json}" "${current_scenario} build;preset" build preset)
if("${baseline_preset}" STREQUAL "" OR "${current_preset}" STREQUAL "")
    zz_invalid("${current_scenario} build;preset" "must not be empty")
endif()
if(NOT "${baseline_preset}" STREQUAL "${current_preset}"
   AND NOT ("${baseline_preset}" STREQUAL "linux-gcc-reference" AND "${current_preset}" STREQUAL "linux-gcc-benchmarks"))
    zz_invalid("${current_scenario} build;preset" "incompatible presets: ${baseline_preset} -> ${current_preset}")
endif()

zz_json_require_type("${baseline_json}" "${current_scenario} metrics" OBJECT metrics)
zz_json_require_type("${current_json}" "${current_scenario} metrics" OBJECT metrics)
zz_json_require_type("${thresholds_json}" "${current_scenario}" OBJECT scenarios "${current_scenario}")
zz_json_require_type("${thresholds_json}" "${current_scenario}" OBJECT scenarios "${current_scenario}" metrics)
string(JSON metric_count ERROR_VARIABLE metric_count_error LENGTH "${baseline_json}" metrics)
if(NOT "${metric_count_error}" STREQUAL "NOTFOUND" OR metric_count LESS 1)
    zz_invalid("${current_scenario} metrics" "baseline metrics must be a non-empty object")
endif()
string(JSON current_metric_count ERROR_VARIABLE current_metric_count_error LENGTH "${current_json}" metrics)
if(NOT "${current_metric_count_error}" STREQUAL "NOTFOUND" OR NOT current_metric_count EQUAL metric_count)
    zz_invalid("${current_scenario} metrics" "baseline/current metric names must match")
endif()
string(JSON threshold_metric_count ERROR_VARIABLE threshold_metric_count_error LENGTH "${thresholds_json}" scenarios "${current_scenario}" metrics)
if(NOT "${threshold_metric_count_error}" STREQUAL "NOTFOUND" OR NOT threshold_metric_count EQUAL metric_count)
    zz_invalid("${current_scenario}" "threshold metrics must exactly cover reporter metrics")
endif()

set(has_gate_failure FALSE)
set(has_observation FALSE)
math(EXPR last_metric_index "${metric_count} - 1")
foreach(metric_index RANGE 0 ${last_metric_index})
    string(JSON metric ERROR_VARIABLE metric_error MEMBER "${baseline_json}" metrics ${metric_index})
    if(NOT "${metric_error}" STREQUAL "NOTFOUND")
        zz_invalid("${current_scenario} metrics" "failed to enumerate baseline metrics")
    endif()
    set(metric_context "${current_scenario}/${metric}")
    zz_json_require_type("${baseline_json}" "${metric_context}" OBJECT metrics "${metric}")
    zz_json_require_type("${current_json}" "${metric_context}" OBJECT metrics "${metric}")
    zz_json_require_type("${thresholds_json}" "${metric_context}" OBJECT scenarios "${current_scenario}" metrics "${metric}")
    zz_json_require_type("${baseline_json}" "${metric_context}" STRING metrics "${metric}" unit)
    zz_json_require_type("${current_json}" "${metric_context}" STRING metrics "${metric}" unit)
    zz_json_get(baseline_unit "${baseline_json}" "${metric_context}" metrics "${metric}" unit)
    zz_json_get(current_unit "${current_json}" "${metric_context}" metrics "${metric}" unit)
    if(NOT "${current_unit}" STREQUAL "${baseline_unit}")
        zz_invalid("${metric_context}" "metric unit mismatch: ${baseline_unit} != ${current_unit}")
    endif()
    zz_json_require_type("${thresholds_json}" "${metric_context}" STRING scenarios "${current_scenario}" metrics "${metric}" metricKind)
    zz_json_get(metric_kind "${thresholds_json}" "${metric_context}" scenarios "${current_scenario}" metrics "${metric}" metricKind)
    if(NOT "${metric_kind}" STREQUAL "statistical-duration" AND NOT "${metric_kind}" STREQUAL "deterministic" AND NOT "${metric_kind}" STREQUAL "sampled-resource")
        zz_invalid("${metric_context}" "metricKind must be statistical-duration, deterministic, or sampled-resource")
    endif()
    foreach(field p95 max)
        zz_json_require_type("${baseline_json}" "${metric_context}.${field}" NUMBER metrics "${metric}" "${field}")
        zz_json_require_type("${current_json}" "${metric_context}.${field}" NUMBER metrics "${metric}" "${field}")
        zz_json_get(baseline_value "${baseline_json}" "${metric_context}.${field}" metrics "${metric}" "${field}")
        zz_json_get(current_value "${current_json}" "${metric_context}.${field}" metrics "${metric}" "${field}")
        zz_json_require_type("${thresholds_json}" "${metric_context}" OBJECT scenarios "${current_scenario}" metrics "${metric}" "${field}")
        zz_json_require_type("${thresholds_json}" "${metric_context}" STRING scenarios "${current_scenario}" metrics "${metric}" "${field}" mode)
        zz_json_require_type("${thresholds_json}" "${metric_context}" NUMBER scenarios "${current_scenario}" metrics "${metric}" "${field}" percent)
        zz_json_get(mode "${thresholds_json}" "${metric_context}" scenarios "${current_scenario}" metrics "${metric}" "${field}" mode)
        zz_json_get(percent "${thresholds_json}" "${metric_context}" scenarios "${current_scenario}" metrics "${metric}" "${field}" percent)
        zz_validate_policy("${current_scenario}" "${metric}" "${metric_kind}" "${field}" "${mode}" "${percent}")
        zz_assert_regression(field_status "${current_scenario}" "${metric}" "${field}" "${baseline_value}" "${current_value}" "${mode}" "${percent}")
        if("${field_status}" STREQUAL "FAIL")
            set(has_gate_failure TRUE)
        elseif("${field_status}" STREQUAL "OBSERVE")
            set(has_observation TRUE)
        endif()
    endforeach()
endforeach()

if(has_gate_failure)
    message(FATAL_ERROR "FAIL ${current_scenario}: one or more gated fields regressed")
elseif(has_observation)
    message(STATUS "OBSERVE ${current_scenario}")
else()
    message(STATUS "PASS ${current_scenario}")
endif()
